apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-deployment
  namespace: jeonbongjun # 네임스페이스 확인
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: ai-service-container
        image: o11117/ai-service:latest
        ports:
        - containerPort: 8000

        readinessProbe:
          httpGet:
            path: /health  # main.py의 /health 엔드포인트
            port: 8000     # ai-svc 포트
          initialDelaySeconds: 15 # 팟 시작 후 15초 뒤 검사 시작
          periodSeconds: 10     # 10초마다 검사

        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: jeonbongjun-secrets
                key: OPENAI_API_KEY
        volumeMounts:
          - name: log-volume
            mountPath: /app/logs

      volumes:
        - name: log-volume
          emptyDir: {}