apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-deployment
  namespace: jeonbongjun # 네임스페이스 확인
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: ai-service-container
        image: o11117/ai-service:latest
        ports:
        # ai-service-service.yaml의 targetPort와 일치
        - containerPort: 8000

        env:
          # --- [유지] API 키 (올바른 설정) ---
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: jeonbongjun-secrets
                key: OPENAI_API_KEY

          # --- [추가] GKE 환경에 맞는 필수 설정값들 ---
          - name: HOST
            value: "0.0.0.0" # 모든 인터페이스에서 수신
          - name: PORT
            value: "8000"    # K8s 서비스 포트와 일치
          - name: DEBUG
            value: "False"   # 운영 환경

          # --- [추가] .env.example에 있던 기타 설정값 ---
          - name: CHROMA_DB_PATH
            value: "/app/embeddings/chromadb" # Dockerfile의 WORKDIR /app 기준
          - name: LOG_LEVEL
            value: "INFO"
          - name: LOG_FILE
            # [중요] log-volume 마운트 경로와 일치
            value: "/app/logs/app.log"

        volumeMounts:
          # --- [유지] 로그 보존을 위한 볼륨 (올바른 설정) ---
          - name: log-volume
            mountPath: /app/logs

      volumes:
        # --- [유지] 팟(Pod) 생명주기 동안 유지되는 임시 볼륨 (올바른 설정) ---
        - name: log-volume
          emptyDir: {}